name: ServerMonitor
version: '${projectVersion}'
description: A Paper plugin to sends the some logs to Discord
main: net.okocraft.servermonitor.paper.PaperServerMonitorPlugin
api-version: '1.20'
folia-supported: true
